### ISSUE TITLE
Could you introduce how to use RLNNET?

### ISSUE THREAD

**Issue by hantaogo** [ZeroLikviz/godot_plugin-neural-network#1]
thanks :)

**Comment by ZeroLikviz** [comment]
Hey there! Just wanted to let you know that I'll be adding an introduction
on how to use RLNNET by this Saturday. In the meantime, if you're eager to
use it right away, you can try to familiarize yourself with the information
I've already written in the RLNNET doc. Happy exploring!

чт, 21 дек. 2023 г., 11:49 Japple ***@***.***>:

**Comment by hantaogo** [comment]
In the past couple of days, I've been studying a bit about neural networks and reinforcement learning. I've also been reading through some source code, and I've found that there are quite a few comments in the code, which has been very helpful. I'm currently working on creating a demo, and I'm very grateful for the assistance.

**Comment by ZeroLikviz** [comment]
I have added an introduction to RLNNET. Also, in case it matters, I want to clarify that RLNNET uses q-learning specifically
