### ISSUE TITLE
question

### ISSUE THREAD

**Issue by emagood** [ZeroLikviz/godot_plugin-neural-network#5]
Error Result :Loss: 0.01074746199776

My Matrix Defined :[0.999999, 0.000000001, 0.00000001, 0.00000001, 0.00000001, 0.00000001, 0.000000001, 0.000000001, 0.000000001, 0.000000001]

Network output: [0.89809935090108, 0.15288818398626, 0.99700603087569, 0.48031210161682, 0.98325232210667, 0.00067422810902, 0.72411411315691, 0.8460514271566, 0.01812945936214, 0.81335536574726]

The error is only 0.0107... 
I missed something 
Matrix 3 and 5 a 100 percent error xD

I'm using this in classification and with deep networks, the network is linear :(

**Comment by ZeroLikviz** [comment]
Hi @emagood, I’ve just made some bug fixes to the NNET class. Could you please copy-paste the updated code into your project and let me know if this resolves the issue? If not, feel free to send me your project, and I’ll take a look to see what might be going wrong.
